title: Event Sourcing Reference Platform
description: Cloud-native event-sourced reference implementation built with .NET 10 and Azure.

theme: minima

markdown: kramdown

plugins:
  - jekyll-seo-tag

collections: {}

defaults:
  -
    scope:
      path: ""
    values:
      layout: default